### ISSUE TITLE
Docker machine setup seems to be failing on some downloads

### ISSUE THREAD

**Issue by gregjan** [helgeho/ArchiveSpark-docker#3]
At UMD we are now trying to use ArchiveSpark and the MHL module to explore that text corpus. I am trying to setup a Jupyter notebook server with all of your modules already installed. This pre-defined docker machine seems the best approach, but I think some of the download links it uses have broken.

Docker log output:

ciber-vs1:~$ docker logs e5e433af8cc2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to archive.apache.org port 80: Connection timed out
tar: spark-2.2.2-bin-hadoop2.7.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat ‘spark-2.2.2-bin-hadoop2.7’: No such file or directory
rm: cannot remove ‘spark-2.2.2-bin-hadoop2.7.tgz’: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to www.l3s.de port 80: Connection timed out
tar: toree2_dynamic_lib.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat ‘toree2_dynamic_lib’: No such file or directory
rm: cannot remove ‘toree2_dynamic_lib.tar.gz’: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:33 --:--:--     0curl: (7) Failed to connect to github.com port 443: Connection timed out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:33 --:--:--     0curl: (7) Failed to connect to github.com port 443: Connection timed out
mv: cannot stat ‘archivespark-assembly-2.7.6.jar’: No such file or directory
mv: cannot stat ‘archivespark-assembly-2.7.6-deps.jar’: No such file or directory
[I 20:48:24.380 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 20:48:24.435 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 20:48:24.435 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 20:48:24.540 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 20:48:24.545 NotebookApp] Running the core application with no additional extensions or settings
[I 20:48:24.556 NotebookApp] Serving notebooks from local directory: /notebooks
[I 20:48:24.556 NotebookApp] 0 active kernels 
[I 20:48:24.556 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 20:48:24.556 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by helgeho** [comment]
Hey Gregory, thanks for getting in touch. Actually, this seems to be an issue at your end though. Since the container is neither able to connect to `l3s.de` nor to `github.com` or `apache.org`, I would assume it does not have internet? Can you please check that?

**Comment by gregjan** [comment]
Many thanks, I had forgotten that I've turned off Docker's iptables mangling. Working fine once I added a network config.

**Comment by helgeho** [comment]
Glad it works now!
